# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh Ghent Photography
email: me@joshghent.com
description: > # this means to ignore newlines until "baseurl:"
  Website for storing all my photograph work as I learn the
  craft.
baseurl: "/photography" # the subpath of your site, e.g. /blog
url: "joshghent.github.io" # the base hostname & protocol for your site
twitter_username: joshghent
github_username:  joshghent
website_url: "https://joshghent.com"

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "photography"
    values:
      permalink: /:path/:basename:output_ext

exclude: [LICENSE-CODE.md, LICENSE-IMAGES, README.md, bower.json]
